#!/bin/bash
water="$WATER"
stir="$STIR"
result_dec=$((5#$(echo "$water" | tr 'water' '01234') + 5#$(echo "$stir" | tr 'stir.' '01234')))
result_bestchol=$(printf "%s" "$result_dec" | bc)
echo "$result_bestchol"
